const { test, expect } = require('@playwright/test');

test.describe('Camera and Mesh Targeting Refactoring', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
    const startButton = page.locator('#start-button');
    if (await startButton.isVisible()) {
      await startButton.click();
    }
    await page.click('#preview-tab');
  });

  test('cameraFollow supports mesh objects, string names, and point_camera_at_mesh block execution', async ({ page }) => {
    const result = await page.evaluate(async () => {
      // 1. Create a box and get its reference
      const testBox = sceneManager.createBox('targetBox', 1, 2, 3);

      // 2. Test cameraFollow with direct mesh object
      sceneManager.cameraFollow(testBox);
      const activeCamera = sceneManager.scene.activeCamera;
      const lockedTargetObj = activeCamera ? activeCamera.lockedTarget : null;

      // 3. Test cameraFollow with string name
      sceneManager.cameraFollow('targetBox');
      const lockedTargetName = activeCamera ? activeCamera.lockedTarget : null;

      // 4. Test code generated by point_camera_at_mesh block (which passes object or variable)
      let blockExecutionResult = null;
      try {
        const testVar = testBox;
        eval("sceneManager.cameraFollow(testVar);");
        blockExecutionResult = activeCamera ? activeCamera.lockedTarget : null;
      } catch (err) {
        blockExecutionResult = err.message;
      }

      return {
        hasObjTarget: lockedTargetObj === testBox,
        hasNameTarget: lockedTargetName === testBox,
        hasBlockTarget: blockExecutionResult === testBox
      };
    });

    expect(result.hasObjTarget).toBe(true);
    expect(result.hasNameTarget).toBe(true);
    expect(result.hasBlockTarget).toBe(true);
  });

  test('setAsPlayer and setFpsCamera support direct mesh objects and string names', async ({ page }) => {
    const result = await page.evaluate(async () => {
      const pBox = sceneManager.createBox('playerBox', 0, 0, 0);

      // setAsPlayer with object
      sceneManager.setAsPlayer(pBox);
      const playerFromObj = sceneManager.player;

      // setAsPlayer with string name
      sceneManager.setAsPlayer('playerBox');
      const playerFromName = sceneManager.player;

      // setFpsCamera with object
      sceneManager.setFpsCamera(pBox);
      const fpsCameraFromObj = sceneManager.scene.activeCamera;
      const parentFromObj = fpsCameraFromObj ? fpsCameraFromObj.parent : null;

      // setFpsCamera with string name
      sceneManager.setFpsCamera('playerBox');
      const fpsCameraFromName = sceneManager.scene.activeCamera;
      const parentFromName = fpsCameraFromName ? fpsCameraFromName.parent : null;

      return {
        playerFromObjMatches: playerFromObj === pBox,
        playerFromNameMatches: playerFromName === pBox,
        parentFromObjMatches: parentFromObj === pBox,
        parentFromNameMatches: parentFromName === pBox
      };
    });

    expect(result.playerFromObjMatches).toBe(true);
    expect(result.playerFromNameMatches).toBe(true);
    expect(result.parentFromObjMatches).toBe(true);
    expect(result.parentFromNameMatches).toBe(true);
  });

  test('onClick and everyFrame support direct mesh objects and string names', async ({ page }) => {
    const result = await page.evaluate(async () => {
      const clickBox = sceneManager.createBox('clickBox', 0, 0, 0);
      let clickedCount = 0;
      let frameCount = 0;

      // Register onClick with mesh object
      sceneManager.onClick(clickBox, () => {
        clickedCount++;
      });

      // Register everyFrame with mesh object
      sceneManager.everyFrame(clickBox, () => {
        frameCount++;
      });

      const hasActionManager = !!clickBox.actionManager;
      const hasPerFrameFunc = sceneManager.perFrameFunctions.some(item => item.targetMesh === clickBox);

      return {
        hasActionManager,
        hasPerFrameFunc
      };
    });

    expect(result.hasActionManager).toBe(true);
    expect(result.hasPerFrameFunc).toBe(true);
  });
});
