name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]
  workflow_dispatch:

# Ensure only one deployment happens at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  call-workflow:
    # Syntax: {owner}/{repo}/.github/workflows/{filename}@{ref}
    uses: digitaledsafety/workflows/.github/workflows/reusable-jekyll-playwright-deploy.yml@main
    with:
      ruby-version: '3.2'
      node-version: '20'
    permissions:
      contents: read
      pages: write
      id-token: write
